services:
  - type: web
    name: puzzl-curation
    runtime: static
    rootDir: curation-web
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 20
    routes:
      - type: redirect
        source: /
        destination: /kimmj
      - type: rewrite
        source: /kimmj
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable
